### ISSUE TITLE
[Twitter Login] Twitter Login(numero incorrecto) - Fail

### ISSUE THREAD

**Issue by Zusetty12** [Zusetty12/PROYECTOTWITTER#17]
#### Precondition
Ingreso de numero de celular no registrado

#### Steps to Reproduce:

| Step | Action | Expected | Status |
| -------- | -------- | -------- | -------- |
| 1| <img src="https://bitmodern-testquality-server-storage.s3.us-west-2.amazonaws.com/attachment_Test_29330.png" alt="" />| | Fail |

**Comment by Zusetty12** [comment]
https://delmesu5.testquality.com defect [D8](https://delmesu5.testquality.com/project/12898/result/2593893/defect/9465).

**Comment by JulianaDamiano** [comment]
Corregido ingresando un número correcto.
